/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/register": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Self-register a new tenant (stellar_card instance) */
        post: operations["registerTenant"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/invoice": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create a CTX gift card order and get payment URL
         * @description stellar_card calls this after an agent creates an order. VCC creates
         *     the CTX order and returns a `web+stellar:pay` URI that stellar_card
         *     pays directly from its treasury wallet.
         *
         *     **Idempotent** per `(tenant_id, order_id)` — a duplicate call
         *     returns the existing invoice without creating a new CTX order.
         */
        post: operations["createInvoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}/paid": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Notify VCC that stellar_card has paid the CTX invoice
         * @description Transitions the job from `invoice_issued` to `queued` and kicks
         *     off the fulfillment pipeline (SSE monitoring → stage1 scrape →
         *     stage2 scrape → callback).
         */
        post: operations["notifyPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs/{jobId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Poll job status (fallback when callback fails) */
        get: operations["getJobStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check for uptime monitors */
        get: operations["healthCheck"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/metrics": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** JSON metrics for dashboards */
        get: operations["getMetrics"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        RegisterResponse: {
            /** Format: uuid */
            tenant_id: string;
            /** @description Bearer token (shown once, starts with 'vcc_') */
            token: string;
            note?: string;
        };
        InvoiceRequest: {
            /** @description stellar_card order UUID */
            order_id: string;
            amount_usdc: string;
            /**
             * Format: uri
             * @description HTTPS URL for the HMAC-signed result callback
             */
            callback_url: string;
            /** @description Shared secret for HMAC signing the callback */
            callback_secret: string;
        };
        InvoiceResponse: {
            /** Format: uuid */
            job_id: string;
            /** @description CTX.com gift card order UUID */
            ctx_order_id: string;
            /** @description web+stellar:pay URI — stellar_card pays this directly */
            payment_url: string;
            /** @description 'already_exists' if this is a duplicate */
            note?: string;
        };
        JobStatus: {
            /** Format: uuid */
            id: string;
            tenant_id: string;
            order_id: string;
            amount_usdc: string;
            ctx_order_id?: string | null;
            /** @enum {string} */
            status: "invoice_issued" | "queued" | "running" | "delivered" | "failed";
            error?: string | null;
            card_brand?: string | null;
            card_last4?: string | null;
            request_id?: string | null;
            /** Format: date-time */
            created_at?: string;
            /** Format: date-time */
            updated_at?: string;
        };
        /**
         * @description POST to callback_url when a job reaches terminal state. Signed
         *     with HMAC-SHA256 v2 (order_id in signing payload). Headers:
         *     X-VCC-Signature, X-VCC-Timestamp, X-VCC-Order-Id, X-Request-ID.
         */
        CallbackPayload: {
            /** Format: uuid */
            order_id: string;
            /** @enum {string} */
            status: "fulfilled" | "failed";
            /** @description Present only when status=fulfilled */
            card?: {
                number?: string;
                cvv?: string;
                expiry?: string;
                brand?: string | null;
            };
            /** @description Present only when status=failed */
            error?: string;
        };
        HealthResponse: {
            ok: boolean;
            frozen: boolean;
            consecutive_failures?: number;
            running_jobs?: number;
            queued_jobs?: number;
        };
        MetricsResponse: {
            frozen_global?: boolean;
            frozen_tenants?: number;
            jobs_last_hour?: {
                [key: string]: number;
            };
            jobs_total?: {
                delivered?: number;
                failed?: number;
                running?: number;
                queued?: number;
                total?: number;
            };
            callback_deadletter_pending?: number;
            /** Format: date-time */
            now?: string;
        };
        ErrorResponse: {
            error: string;
            message?: string;
        };
    };
    responses: {
        /** @description Invalid request */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Missing or invalid token */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Resource not found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    registerTenant: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": {
                    /** @description Human-readable tenant label */
                    label?: string;
                };
            };
        };
        responses: {
            /** @description Tenant created, token shown once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegisterResponse"];
                };
            };
            /** @description Rate limited (10/hour/IP) */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    createInvoice: {
        parameters: {
            query?: never;
            header?: {
                /** @description Correlation ID from stellar_card for end-to-end tracing */
                "X-Request-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InvoiceRequest"];
            };
        };
        responses: {
            /** @description Duplicate — existing invoice returned */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            /** @description Invoice created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InvoiceResponse"];
                };
            };
            400: components["responses"]["BadRequest"];
            401: components["responses"]["Unauthorized"];
            /** @description CTX order creation failed */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description VCC fulfillment system is frozen */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    notifyPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK (may include note already_queued for idempotent calls) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        ok?: boolean;
                        note?: string;
                    };
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    getJobStatus: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                jobId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job details (sensitive card fields stripped) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobStatus"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    healthCheck: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System healthy */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description System frozen */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    getMetrics: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description System metrics */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MetricsResponse"];
                };
            };
        };
    };
}
